### PR TITLE
Fix beforeunload API

### LINKED ISSUE #1093: force closeBrowser or reload
### Expected behavior
There should be a flag or new option to force a close or reload page

### Actual behavior
Browser will not close as changes are not saved

Screen Shot 2020-02-19 at 9 51 16 AM

Console:
Failed to capture screenshot on failure.
Error: WebSocket is not open: readyState 3 (CLOSED)
    Error Message: Error: Timed out
    Stacktrace: 
    Error: Timed out
        at Timeout.<anonymous> (/Users/dsolis/.gauge/plugins/js/2.3.7/src/test.js:43:23)
        at ontimeout (timers.js:436:11)
        at tryOnTimeout (timers.js:300:5)
        at listOnTimeout (timers.js:263:5)
        at Timer.processTimers (timers.js:223:10)

### Steps to reproduce
1. Open a page with Edit (do not save changes)
2. Try to close the browser
3.  Chrome displays a popup with Leave site question...

### Versions
```
Daniel-Solis-MacBook-Pro:gauge-tests daniel.solis$ node --version
v10.16.0
Daniel-Solis-MacBook-Pro:gauge-tests daniel.solis$ taiko --version
Version: 1.0.3 (Chromium: 81.0.3994.0) RELEASE
```

Is there a working work around?

Thanks in advance

### PR DESCRIPTION
**Pull request by negiDharmendra**
Fixes #1093

### CODE REVIEW

File: lib/handlers/pageHandler.js [hunk 1]
```diff
@@ -43,8 +43,16 @@ eventHandler.on('createdSession', async client => {
...
     eventHandler.emit(p.name, p);
   });
-  page.javascriptDialogOpening(({ message, type }) => {
-    eventHandler.emit(createJsDialogEventName(message, type), {
+  page.javascriptDialogOpening(({ message, type, url }) => {
+    const eventName = createJsDialogEventName(message, type);
+    if (!eventHandler.listenerCount(eventName)) {
+      console.warn(
+        `There is no handler registered for ${type} popup displayed on the page ${url}.
+This might interfare with your test flow. You can use Taiko's ${type} API to handle this popup.
```
Comment (sriv) [inline lib/handlers/pageHandler.js:51]: interfare -> interfere
