### PR TITLE
Remove element wrapper list

### LINKED ISSUE #1341: elements(), element(index) and ElementWrapperList is missing from Typescript type definitions
# Expected behavior
`elements()` and `element(index)` from https://docs.taiko.dev/#elementwrapperlist is available in type definitions

### Actual behavior
`elements()`, `element(index)` and `ElementWrapperList` is not available in type definitions

### Steps to reproduce
Try to use `elements()` or `element(index)` in a typescript project.

### Versions
```
`taiko 1.0.12`
```

### PR DESCRIPTION
**Pull request by jfgreffier**
Fixes #1341

### CODE REVIEW

File: lib/taiko.js [hunk 1]
```diff
@@ -3159,48 +3159,6 @@ const rectangle = async (selector, callback) => {
  *
  */
 
-/**
```
Comment (NivedhaSenthil) [inline lib/taiko.js:3162]: These are properties of ElementWrapper, and the existing ElementWrapper definition has to be updated to Element. It has to be updated and not removed.

Comment (jfgreffier) [reply lib/taiko.js:3162]: Pushing corrections. Thanks for the pointer

I also fixed the types definitions the best I could by adding methods from different Elements, in the same manner that it was done with ElementWrapper
