### PR TITLE
Fix close browser

### LINKED ISSUE #818: Taiko should fail if user tries to open or close browser multiple times.
**Actual Behaviour**
If openBrowser is called multiple times, multiple chromium instances are launched. Taiko retains the references and the CRI connection only to the most recent chromium instance.

If close Browser is called multiple times, Taiko is able to close only the most recent chromium instance. Since, the references to other chromium instances are lost, it fails to close them.
```
TypeError: Cannot read property ‘removeAllListeners’ of null
       at Chrome.reconnect (...../...../....../node_modules/taiko/lib/taiko.js:137:13)
       at Chrome.emit (events.js:198:13)
       at WebSocket._ws.on (...../...../....../node_modules/chrome-remote-interface/lib/chrome.js:233:22)
       at WebSocket.emit (events.js:198:13)
       at WebSocket.emitClose (...../...../....../node_modules/ws/lib/websocket.js:191:10)
       at Socket.socketOnClose (...../...../....../node_modules/ws/lib/websocket.js:850:15)
       at Socket.emit (events.js:198:13)
       at TCP._handle.close (net.js:606:12)
```
**Expected Behaviour**
Taiko should throw an error to user mentioning that openBrowser cannot be called again as there is a chromium instance open(closeBrowser is not yet called).

Taiko should fail with appropriate message, if close browser is called multiple times without calling openBrowser.

### PR DESCRIPTION
**Pull request by NivedhaSenthil**
Fixes #818 #1166

### CODE REVIEW

File: lib/taiko.js [hunk 1]
```diff
@@ -3338,9 +3338,12 @@ const evaluate = async (selector, func) => {
 };
 
 const validate = () => {
-  if (!dom || !page) {
+  if (!_client) {
     throw new Error('Browser or page not initialized. Call `openBrowser()` before using this API');
   }
+  if (_client._ws.readyState > 1) {
+    throw new Error('Connection to Browser closed. Try reconnecting by `openBrowser()`');
```
Comment (sriv) [inline lib/taiko.js:3345]: If browser instance is already running, `openBrowser` will error out stating only one instance is allowed. If there isn't a browser instance, it will launch a new one, but we cannot consider that as 'reconnecting'

Comment (NivedhaSenthil) [reply lib/taiko.js]: Updated the messaging to reflect if the browser instance is closed.

File: lib/taiko.js [hunk 2]
```diff
@@ -3338,9 +3338,17 @@ const evaluate = async (selector, func) => {
...
 
 const validate = () => {
-  if (!dom || !page) {
+  if (!_client) {
     throw new Error('Browser or page not initialized. Call `openBrowser()` before using this API');
   }
+  if (_client._ws.readyState > 1) {
+    if (chromeProcess && chromeProcess.killed) {
+      throw new Error(
+        'Browser is closed due to `closeBrowser()` or crash. Try reopening by `openBrowser()`',
```
Comment (sriv) [inline lib/taiko.js:3347]: Suggestion:

`The Browser instance was closed either via 'closeBrowser()' call, or it crashed for reasons unknown to Taiko. You can try launching a fresh instance using 'openBrowser()' or inspect the logs for details of the possible crash.`

File: lib/taiko.js [hunk 3]
```diff
@@ -3338,9 +3338,17 @@ const evaluate = async (selector, func) => {
...
+      );
+    }
+    throw new Error('Connection to browser lost');
```
Comment (sriv) [inline lib/taiko.js:3350]: Suggestion:

`Connection to browser lost. This probably isn't a problem with Taiko, inspect logs for possible causes.`
