### PR TITLE
#279 Drag and drop support for html5 draggable elements

### LINKED ISSUE #279: Drag and drop does not work as expected for HTML5 draggable elements
### Expected behavior
Should be able to drag and drop HTML5 draggable elements.

### Actual behavior
Drag works fine but gets dropped to current cursor position instead of given position.

### Steps to reproduce
```
(async () => {
    try {
        await openBrowser();
        await goto("https://gojs.net/latest/samples/htmlDragDrop.html");
        await dragAndDrop("Coffee",into($('canvas')));
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```
Upstream issue for the same ChromeDevTools/devtools-protocol#130

### PR DESCRIPTION
**Pull request by NivedhaSenthil**
Fixes #279

### CODE REVIEW

File: lib/elements/element.js [hunk 1]
```diff
@@ -52,7 +52,21 @@ class Element {
       returnByValue: true,
     });
     if (result.value === undefined) {
-      throw new Error(`${this.description} does not have disable attribute`);
+      return false;
+    }
+    return result.value;
+  }
+
+  async isDraggable() {
```
Comment (zabil) [inline lib/elements/element.js:60]: Can we document this API?

Comment (NivedhaSenthil) [reply lib/elements/element.js:60]: It has to be exposed from element wrapper also then, will do
