### PR TITLE
Fix switchTo to accept regex

### LINKED ISSUE #1147: switchTo() doesn't support RegEx's anymore
There seems to be a bug in `lib/taiko.js` on line 418-422. This function isn't present on a RegEx. The call could be moved. The tests should probably also be updated to test for this use case.

Alternatively this should be removed from the docs.

### Expected behavior
Calling `switchTo(/http(s):\/\/www.google.com/)` is a valid use case.

### Actual behavior
A TypeError is thrown:
```
Error Message: TypeError: arg.trim is not a function
        Stacktrace: 
        TypeError: arg.trim is not a function
            at module.exports.switchTo (node_modules/taiko/lib/taiko.js:419:13)
            at module.exports.<computed> (node_modules/taiko/lib/taiko.js:3225:36)
            at Object.<anonymous> (tests/login.js:70:9)
```

### Steps to reproduce
1. Create a taiko step
2. Call switchTo(/http/)

### Versions
```
$ node --version
v13.11.0

$ taiko --version
Version: 1.0.5 (Chromium: 81.0.3994.0) RELEASE
```

### PR DESCRIPTION
**Pull request by NivedhaSenthil**
- update empty string check
- add tests for regex switchTo
- update wait for readystate to timeout on navigation timeout instead of default.

Fixes #1147

### CODE REVIEW

**Comment by BugDiver** [comment]
> @NivedhaSenthil Thank you for contributing to taiko. Your pull request has been labeled as a release candidate 🎉🎉.
> 
> Merging this PR will trigger a release.
> 
> ### Please bump up the version as part of this PR.
> Instructions to bump the version can found at [CONTRIBUTING.md](https://github.com/getgauge/taiko/blob/master/CONTRIBUTING.md)
> 
> If the CONTRIBUTING.md file does not exist or does not include instructions about bumping up the version, please looks previous commits in git history to see what changes need to be done.

This won't be needed. The verison is alread updated.

File: lib/doActionAwaitingNavigation.js [hunk 1]
```diff
@@ -112,10 +112,10 @@ const waitForNavigation = (timeout, promises = []) => {
             );
           },
           defaultConfig.retryInterval,
-          defaultConfig.retryTimeout,
+          timeout,
         )
           .then(resolve)
-          .catch(reject);
+          .catch(() => reject('Timedout'));
```
Comment (sriv) [inline lib/doActionAwaitingNavigation.js]: Won't this cause all errors to be rejected with `Timedout`?

File: lib/doActionAwaitingNavigation.js [hunk 2]
```diff
@@ -112,10 +112,10 @@ const waitForNavigation = (timeout, promises = []) => {
             );
           },
           defaultConfig.retryInterval,
-          defaultConfig.retryTimeout,
+          timeout,
```
Comment (sriv) [inline lib/doActionAwaitingNavigation.js]: why should this be changed? `timeout` is used below to reject when timer expires.

File: lib/doActionAwaitingNavigation.js (hunk 1 above)
Comment (NivedhaSenthil) [reply lib/doActionAwaitingNavigation.js]: only waiting for readyState to be complete will get rejected with Timedout

File: lib/doActionAwaitingNavigation.js (hunk 2 above)
Comment (NivedhaSenthil) [reply lib/doActionAwaitingNavigation.js]: To honour the user given navigation timeout.. if default is used this can timeout before the user given time and the promise will get rejected.
