### PR TITLE
Fix: evaluate returns empty object when function throws (#2613)

### LINKED ISSUE #2613: evaluate returns empty object when function throws
**Describe the bug**

```js
const x = await evaluate(() => {
  return document.querySelector('.doesNotExist').textContent
})
```

When no element with class `doesNotExist` exists `x` will have value `{}`. I think this is because it's a json-ified error. 

**To Reproduce**

```js
const { openBrowser, evaluate, goto } = require('taiko');
openBrowser();
goto('https://example.com')
const x = await evaluate(() => {
  return document.querySelector('.doesNotExist').textContent
})
console.log(x);
```

**Expected behavior**

`evaluate` should throw when the client function throws. It might require wrapping the function and returning an either type which includes the message and the stack of the error.

### PR DESCRIPTION
**Pull request by NajoroRabiaza**
Description
This PR fixes the issue where evaluate swallows exceptions thrown inside the browser context and returns an empty object.

Changes:

Checked for result.exceptionDetails in CDP response inside doActionAwaitingNavigation.
If an exception occurred, throw a standard Error in the Node context with the browser's serialized error message.
Also added a unit test to prevent future regressions.

Fixes #2613

### CODE REVIEW

File: packages/taiko/lib/taiko.js [hunk 1]
```diff
@@ -2367,6 +2367,15 @@ module.exports.evaluate = async (selector, callback, options = {}) => {
     });
   });
 
+  if (result && result.exceptionDetails) {
+    const exceptionDetails = result.exceptionDetails;
+    const errorMessage =
+      exceptionDetails.exception && exceptionDetails.exception.description
+        ? exceptionDetails.exception.description
+        : exceptionDetails.text || "Error in evaluate callback";
```
Comment (zabil) [inline packages/taiko/lib/taiko.js]: Can we change this to
```
 const errorMessage =
   exceptionDetails.exception?.description ??
   exceptionDetails.text ??
   "Error in evaluate callback";
```

File: tests/unit-tests/evaluate.test.js [hunk 2]
```diff
@@ -103,6 +103,19 @@ describe(testName, () => {
       expect(actual).to.equal(testName);
     });
 
+    it("should throw when the callback throws an error", async () => {
```
Comment (zabil) [inline tests/unit-tests/evaluate.test.js:106]: Have you tried 

```
 it("should throw when the callback throws an error", async () => {
   await expect(
     evaluate(() => document.querySelector(".doesNotExist").textContent)
   ).to.be.rejectedWith(Error, /TypeError/);
 });
```

**Review by zabil — CHANGES_REQUESTED** [review]

File: packages/taiko/lib/taiko.js (hunk 1 above)
Comment (NajoroRabiaza) [reply packages/taiko/lib/taiko.js]: Yes, that's updated

File: tests/unit-tests/evaluate.test.js (hunk 2 above)
Comment (NajoroRabiaza) [reply tests/unit-tests/evaluate.test.js:106]: Yeah tried it, Didn't think of rejectedWith, cleaner indeed. Updated!

**Comment by zabil** [comment]
@NajoroRabiaza can you please sign the dco? https://github.com/getgauge/taiko/pull/2772/checks?check_run_id=71931483978

**Review by NivedhaSenthil — APPROVED** [review]

**Review by zabil — APPROVED** [review]
